version: '3.9'

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: login
      MYSQL_DATABASE: db


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'

  bot:
    container_name: qabot
    build:
      context: ..
      dockerfile: ./docker/bot/Dockerfile
