wtf_sticker_list = [
    'CAACAgIAAxkBAAIEaWH5cnnNYr70hDodfb4bmgIeAAE7dwACex8AAulVBRjkuOTEW319pCME',
    'CAACAgIAAxkBAAIEamH5cui4ksHvR4GkVbdYiBEco2MgAAJFEwAC0KsRSoe4yPjya3E-IwQ',
    'CAACAgIAAxkBAAIEa2H5cx6OmlXd-sLwNFm6jqwfhVLpAAJsHQAC6VUFGFW2CoiFHO3aIwQ',
    'CAACAgIAAxkBAAIEbGH5c0RKlkkD64qI4Xrkzt7BmygVAAL4AgACRxVoCcorUKIdIVU-IwQ',
]
